### model
model_name_or_path: /data/ckpt/deepseek/deepseek-6.7b/

### method
stage: pt
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: src/configs/deepspeed/ds_z3_config.json

### dataset
dataset: shuffled_pretrain
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/ckpt/wangning/outputs/pretrain_test
logging_steps: 1
save_steps: 30
plot_loss: true
save_only_model: True
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: constant
bf16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500

