
### model
model_name_or_path: /path/to/your/model
adapter_name_or_path: /path/to/your/adapter
template: deepseekcoder_mine
finetuning_type: lora

### export
export_dir: /path/to/your/export/dir
export_size: 5
export_device: cuda
export_legacy_format: false