### model
model_name_or_path: /data/ckpt/wangning/deepseek-7B/pretrain2

### method
stage: ppo_compiler
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

### ddp
ddp_timeout: 180000000

### dataset
dataset: instruct_openscores_ast
template: deepseekcoder_mine
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/ckpt/wangning/outputs/ppo_compiler_instruct_test
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 0.00001
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### generate
max_new_tokens: 2048
top_p: 0.95
temperature: 0.2